apiVersion: v1
kind: PersistentVolume
metadata:
  name: aelita-pv-pipelines
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: aelita-pipelines
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: aelita-pv-caches
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: aelita-caches
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: aelita-pv-configs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: aelita-configs
    fsType: ext4

