apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-caches
  labels:
    type: postgres-caches
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgres-caches
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-caches
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-configs
  labels:
    type: postgres-configs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgres-configs
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-configs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pipelines
  labels:
    type: postgres-pipelines
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgres-pipelines
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

