apiVersion: v1
kind: Service
metadata:
  name: aelita
spec:
  type: LoadBalancer
  ports:
    - name: github-notice
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: github-status
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: queue-view
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: aelita

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aelita-pv-claim
  labels:
    app: aelita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aelita
spec:
  # TODO #42
  # We cannot properly replicate because the GitHub team cache is stored in-
  # memory and update by webhooks, so the different instances will fall out
  # of sync.
  replicas: 1
  template:
    metadata:
      labels:
        app: aelita
    spec:
      containers:
        - name: aelita
          image: gcr.io/aelita-1374/aelita:INSERT_CURRENT_VERION_HERE
          ports:
            - containerPort: 5000
            - containerPort: 6000
            - containerPort: 8000
          volumeMounts:
            - mountPath: /data
              name: aelita-data
        #- name: aelita-sh
          #image: busybox
          #command: [ "sleep", "1000000000000" ]
          #volumeMounts:
            #- mountPath: /data
              #name: aelita-data
      volumes:
        - name: aelita-data
          persistentVolumeClaim:
            claimName: aelita-pv-claim

